# ─── USP Airline — Mosquitto MQTT Broker Config ───────────────────────────

# Conexões
# Listener MQTT padrão usado pelos aviões e pelo servidor de aplicação.
listener 1883
protocol mqtt

# Listener WebSocket usado pelo frontend quando necessário.
listener 9001
protocol websockets

# Autenticação
# O projeto roda em ambiente simulado, permitindo acesso anônimo.
allow_anonymous true

# Persistência
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

# Limites de entrega
# QoS 0 é suficiente para telemetria, fire-and-forget, que pode ser perdida sem problemas.
# QoS 1 é usado para eventos de ciclo de vida, que não devem ser perdidos.
max_qos 1

# Tamanho máximo de mensagens JSON, que são enviadas pelos aviões e pelo servidor de aplicação.
max_packet_size 65536

# Filas internas
# Evita sobrecarga caso muitos clientes fiquem conectados ao mesmo tempo.
max_inflight_messages 100
max_queued_messages 1000

# Bridges - Pontes de Federação
# Compartilha a telemetria entre brokers sem criar loops de mensagens, pois o out 1 garante que cada mensagem seja enviada apenas uma vez para cada broker remoto.

connection ponte_sul
address broker_sul:1883
topic voo/# out 1 "" ""

connection ponte_sudeste
address broker_sudeste:1883
topic voo/# out 1 "" ""

connection ponte_norte
address broker_norte:1883
topic voo/# out 1 "" ""

connection ponte_nordeste
address broker_nordeste:1883
topic voo/# out 1 "" ""

connection ponte_centro_oeste
address broker_centro_oeste:1883
topic voo/# out 1 "" ""