# ─── USP Airline — Mosquitto MQTT Broker Config ───────────────────────────

# Conexões
# Listener MQTT padrão usado pelos aviões e pelo servidor de aplicação.
listener 1883
protocol mqtt

# Listener WebSocket usado pelo frontend quando necessário.
listener 9001
protocol websockets

# Autenticação
# O projeto roda em ambiente simulado, permitindo acesso anônimo.
allow_anonymous true

# Persistência
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

# Qualidade de serviço máxima permitida
max_qos 1

# Tamanho máximo de mensagens JSON, que são enviadas pelos aviões e pelo servidor de aplicação.
max_packet_size 65536

# Filas internas
# Evita sobrecarga caso muitos clientes fiquem conectados ao mesmo tempo.
max_inflight_messages 100
max_queued_messages 1000

#Modo desenvolvimento não ocorrerá bridges, pois não há outros brokers para se conectar. As bridges são usadas apenas em produção, ou seja, por meio do docker-compose.prod.yml.